#include "fcse.h"

/**
 * @brief Check if FCSE is active.
 * 
 * @return byte Boolean value of 1 when active and 0 when not active.
 */
byte FCSE_is_active() {
    return (*CP15_Reg.regs[PROC_ID] >> 25) == 0 ? 0 : 1;
}

/**
 * @brief Translate virtual address to modified virtual address.
 * 
 * @param va Virtual address generated by the ARM CPU.
 * @return word Modified Virtual address translated by the FCSE.
 */
word FCSE_from_va_to_mva(word va) {
    word PID = *CP15_Reg.regs[PROC_ID] >> 25;
    if ((va >> 25) == 0b0000000) {
        return va | (PID << 25);
    } else return va;
}